// automatically generated by rust-bindgen

#![allow(dead_code)]
use enigma_types::*;
use sgx_types::*;

extern "C" {
    pub fn ocall_get_home(output: *mut u8, result_length: *mut u32) -> sgx_status_t;
}
extern "C" {
    pub fn ocall_save_to_memory(retval: *mut u64, data_ptr: *const u8, data_len: usize) -> sgx_status_t;
}
